# Generated by Django 3.0.3 on 2020-02-20 17:46

from django.db import migrations, models
import django.db.models.deletion
import maptool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='map title')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('map_image', models.ImageField(height_field='image_height', max_length=255, null=True, upload_to='maps/', validators=[maptool.models.validate_image], width_field='image_width')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('in_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='game.Game')),
            ],
            options={
                'verbose_name': 'map',
                'verbose_name_plural': 'maps',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='map',
            index=models.Index(fields=['creation_date'], name='maptool_map_creatio_590474_idx'),
        ),
    ]
